from __future__ import annotations

from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.models.db_models import Alert
from app.services.alert_service import get_timeline
from sqlalchemy.orm import Session


def build_incident_pdf(db: Session, alert: Alert, generated_by: str = "CivicIQ") -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title=f"CivicIQ Incident Brief {alert.alert_id}")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("CivicIQ NCR Decision Intelligence Platform", styles["Title"]),
        Paragraph(f"Incident Brief: {alert.title}", styles["Heading1"]),
        Spacer(1, 12),
    ]
    fields = [
        ("Alert ID", alert.alert_id),
        ("District", alert.district_name),
        ("Category", alert.category),
        ("Severity", alert.severity),
        ("Priority", alert.priority),
        ("Status", alert.status),
        ("Assigned Department", alert.assigned_department),
        ("Created", alert.created_at.isoformat()),
        ("Updated", alert.updated_at.isoformat()),
        ("SLA Status", alert.sla_status),
        ("Escalation Status", alert.escalation_status),
        ("Generated By", generated_by),
        ("Generated At", datetime.utcnow().isoformat(timespec="seconds") + "Z"),
    ]
    for label, value in fields:
        story.append(Paragraph(f"<b>{label}:</b> {value or '-'}", styles["BodyText"]))
    story.extend([Spacer(1, 12), Paragraph("Situation Summary", styles["Heading2"]), Paragraph(alert.description, styles["BodyText"])])
    story.extend([Spacer(1, 8), Paragraph("Evidence and Data Sources", styles["Heading2"]), Paragraph(alert.source, styles["BodyText"])])
    story.extend([Spacer(1, 8), Paragraph("Risk Assessment", styles["Heading2"]), Paragraph(f"{alert.severity} / {alert.priority}", styles["BodyText"])])
    story.extend([Spacer(1, 8), Paragraph("Recommended Actions", styles["Heading2"])])
    import json

    for action in json.loads(alert.recommended_actions or "[]") or ["Validate signal with district control room."]:
        story.append(Paragraph(f"- {action}", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Notes Timeline", styles["Heading2"])])
    for event in get_timeline(db, alert.alert_id):
        story.append(Paragraph(f"{event['created_at']} - {event['event_type']}: {event['message']}", styles["BodyText"]))
    story.extend(
        [
            Spacer(1, 12),
            Paragraph(
                "Disclaimer: This is an AI-assisted decision support brief and should be validated by authorized officials.",
                styles["Italic"],
            ),
        ]
    )
    doc.build(story)
    return buffer.getvalue()
